
enum MeasuresGoal {
  WEIGHT_GOAL, BODY_FAT_PERCENTAGE_GOAL, SHOULDERS_GOAL, LEFT_FOREARM_GOAL, RIGHT_FOREARM_GOAL, UPPER_ABS_GOAL, LOWER_ABS_GOAL, WAIST_GOAL, 
  HIPS_GOAL, LEFT_THIGH_GOAL, RIGHT_THIGH_GOAL, LEFT_CALF_GOAL, RIGHT_CALF_GOAL, LEFT_TRICEP_GOAL, RIGHT_TRICEP_GOAL, CHEST_GOAL, LEFT_BICEP_GOAL,
  RIGHT_BICEP_GOAL, NECK_GOAL,
}

final EnumValues<MeasuresGoal> measuresGoalValues = EnumValues<MeasuresGoal> (<String, Measures> {
    'WEIGHT_GOAL': Measures.WEIGHT_GOAL, 
    'BODY_FAT_PERCENTAGE_GOAL': Measures.BODY_FAT_PERCENTAGE_GOAL, 
    'SHOULDERS_GOAL': Measures.SHOULDERS_GOAL, 
    'LEFT_FOREARM_GOAL': Measures.LEFT_FOREARM_GOAL, 
    'RIGHT_FOREARM_GOAL': Measures.RIGHT_FOREARM_GOAL, 
    'UPPER_ABS_GOAL': Measures.UPPER_ABS_GOAL, 
    'LOWER_ABS_GOAL': Measures.LOWER_ABS_GOAL, 
    'WAIST_GOAL': Measures.WAIST_GOAL, 
    'HIPS_GOAL': Measures.HIPS_GOAL, 
    'LEFT_THIGH_GOAL': Measures.LEFT_THIGH_GOAL, 
    'RIGHT_THIGH_GOAL': Measures.RIGHT_THIGH_GOAL, 
    'LEFT_CALF_GOAL': Measures.LEFT_CALF_GOAL, 
    'RIGHT_CALF_GOAL': Measures.RIGHT_CALF_GOAL, 
    'LEFT_TRICEP_GOAL': Measures.LEFT_TRICEP_GOAL, 
    'RIGHT_TRICEP_GOAL': Measures.RIGHT_TRICEP_GOAL, 
    'CHEST_GOAL': Measures.CHEST_GOAL, 
    'LEFT_BICEP_GOAL': Measures.LEFT_BICEP_GOAL,
    'RIGHT_BICEP_GOAL': Measures.RIGHT_BICEP_GOAL, 
    'NECK_GOAL': Measures.NECK_GOAL,
});


