os:
 - linux
  
sudo: false

language: dart

dart: 
# Install the latest stable release
 - stable
 
dart_task:
# Run the test on the platform's dart vm by default 
 - test: --platform vm
# Warnings are fatal, but we only analyze the lib/ directory.
 - dartanalyzer: --fatal-warnings lib
# Verify that all the files are properly formatted
 - dartfmt: true

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
cache:
  directories:
- $HOME/.pub-cache
 
 notifications:
  email:
   recipients: 
    - axel.hpm.coudray@gmail.com
   on_success: never 
   on_failure: always
   

 
